name = "Trace"
uuid = "afc56b53-c9a9-482a-a956-d1d800e05558"
authors = ["Anton Smirnov <17990405+pxl-th@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Assimp = "079381af-6941-5802-8ad5-fb13e7f1c93a"
Clang = "40e3b903-d033-50b4-a0cc-940c62c95e31"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
assimp_win_jll = "fe2041e4-48f9-56de-9ac5-7523ba92ef05"
